# General Params
verbosity: 3
use_threadsafe_submap_collection: true
use_transform_caching: true
transform_lookup_time: 0.1
global_frame_name: world
visualization_interval: -1.0
data_logging_interval: -1.0
print_timing_interval: 0.0
max_input_queue_length: 1000
ros_spinning_threads: 8

labels:
  type: csv
  file_name: /home/lukas/Documents/Datasets/rio_sequences/groundtruth_labels.csv

camera:
  verbosity: 1
  width: 224
  height: 172
  vx: 113.696
  vy: 85.4004
  fx: 176.523
  fy: 240.667
  max_range: 5  # m
  min_range: 0.1
  
submap_allocator:
  type: semantic  # semantic
  verbosity: 1   
  
  # submaps
  voxels_per_side: &voxels_per_side 16
  truncation_distance: -2 # negative = #vs
  use_class_layer: true
  
  # Meshing
  clear_foreign_voxels: false
  required_belonging_corners: 4
  
  # Semantic
  small_instance_voxel_size: 0.02
  medium_instance_voxel_size: 0.03
  large_instance_voxel_size: 0.04
  background_voxel_size: 0.05
  unknown_voxel_size: 0.05
  
freespace_allocator:
  type: monolithic  # monolithic
  verbosity: 1  
  voxels_per_side: *voxels_per_side 
  truncation_distance: -2   
  voxel_size: 0.3

id_tracker:
  type: projective # ground_truth, projective, detectron, single_tsdf
  verbosity: 1
  
  # Projective ID tracker
  depth_tolerance: -1  # m, negative = #vs
  tracking_metric: IoU  # IoU, overlap
  match_acceptance_threshold: 0.1  
  min_allocation_size: 2000 # px, for submap allocation.
  use_class_data_for_matching: true  

tsdf_integrator:  
  type: class_projective # projective, class_projective, single_tsdf
  verbosity: 1     

  # Projective
  use_weight_dropoff: true
  max_weight: 10000
  interpolation_method: adaptive  # nearest, bilinear, adaptive
  foreign_rays_clear: true
  integration_threads: 8
  allocate_neighboring_blocks: true
  
  # Class Projective
  use_binary_classification: true
  use_instance_classification: &use_instance_classification false
  update_only_tracked_submaps: true
  
map_management:
  type: submaps
  verbosity: 4
  
  # Frequencies
  prune_active_blocks_frequency: 1 
  activity_management_frequency: 1
  change_detection_frequency: 5
  
  # Behavior
  merge_deactivated_submaps_if_possible: true
  apply_class_layer_when_deactivating_submaps: false
  
  activity_manager:
    required_reobservations: 5 # Consecutive observations to keep new submaps.
    deactivate_after_missed_detections: 5  # Deactivate submaps when not observed for x frames.
  
  tsdf_registrator:
    verbosity: 3
    min_voxel_weight: 0.000001
    error_threshold: -1 # m, negative = #vs
    match_rejection_points: 20  
    match_rejection_percentage: 0.02
    match_acceptance_points: 20
    match_acceptance_percentage: 0.02
    normalize_by_voxel_weight: true
    
  layer_manipulator:
      verbosity: 3
      use_instance_classification: *use_instance_classification
  
visualization:  
  submaps:
    type: submaps  # submaps, single_tsdf
    verbosity: 1
    color_mode: submaps # submaps, instances, color, normals, classes, change, classification
    visualization_mode: active  # all, active, active_only, inactive, persistent
    submap_color_discretization: 20
    visualize_mesh: true
    visualize_tsdf_blocks: true
    visualize_free_space: true
    visualize_bounding_volumes: true
    include_free_space: false
    mesh_min_weight: 0.000001
  
  planning:
    verbosity: 1
    visualize_slice: true
    slice_resolution: 0.1
    slice_height: -0.5
  
  tracking:
    verbosity: 1
    visualize_tracking: true
