# General Params
verbosity: 3
use_threadsafe_submap_collection: true
use_transform_caching: true
transform_lookup_time: 0.1
global_frame_name: world
visualization_interval: -1.0
data_logging_interval: -1.0
print_timing_interval: 0.0
max_input_queue_length: 1000
ros_spinning_threads: 8

camera:
  verbosity: 3
  width: 640  # Px
  height: 480
  vx: 319.500000
  vy: 239.500000
  fx: 577.870605
  fy: 577.870605
  max_range: 5  # m
  min_range: 0.1

id_tracker:
  type: single_tsdf
  verbosity: 3
  # Single TSDF
  voxel_size: 0.05
  truncation_distance: -2
  voxels_per_side: 16
  use_class_layer: true
  use_detectron: false
  use_instance_classification: false
  classification:
    type: fixed_count

tsdf_integrator:
  type: single_tsdf
  verbosity: 3
  # Projective
  use_weight_dropoff: true
  max_weight: 10000
  interpolation_method: adaptive  # nearest, bilinear, adaptive
  integration_threads: 8
  use_color: true
  use_segmentation: true
  use_uncertainty: false

visualization:
  submaps:
    type: single_tsdf
    verbosity: 1
    color_mode: classes # color, normals, classes, instances, classification
    visualization_mode: all  # all
    submap_color_discretization: 20
    visualize_mesh: true
    visualize_tsdf_blocks: true
    visualize_free_space: true
    visualize_bounding_volumes: true
    include_free_space: true
    mesh_min_weight: 0.000001

  planning:
    verbosity: 1
    visualize_slice: true
    slice_resolution: 0.1
    slice_height: -0.5

  tracking:
    verbosity: 1
    visualize_tracking: true
