# General Params
verbosity: 99
use_threadsafe_submap_collection: true
use_transform_caching: false
transform_lookup_time: 0.1
global_frame_name: world
visualization_interval: 1.0
data_logging_interval: -1.0
print_timing_interval: 0.0
max_input_queue_length: 1000
ros_spinning_threads: 8
max_delay: 0.3
use_class_layer: true

labels:
  type: csv
  file_name: /home/rene/thesis/panoptic/detectron_labels.csv
  verbosity: 99

camera:
  verbosity: 99
  width: 640  # Px
  height: 480
  vx: 320
  vy: 240
  fx: 320
  fy: 320
  max_range: 3.5  # m
  min_range: 0.1

id_tracker:
  type: single_tsdf
  verbosity: 99

  use_class_layer: true
  # Single TSDF
  voxel_size: 0.05
  truncation_distance: -4
  voxels_per_side: 16
  use_detectron: false
  use_instance_classification: false

tsdf_integrator:
  type: single_tsdf
  verbosity: 99

  # Projective
  use_weight_dropoff: true
  max_weight: 10000
  interpolation_method: adaptive  # nearest, bilinear, adaptive
  integration_threads: 8
  use_uncertainty: true

visualization:
  submaps:
    type: single_tsdf
    verbosity: 99
    color_mode: color # color, normals, classes, instances, classification
    visualization_mode: all  # all
    submap_color_discretization: 20
    visualize_mesh: true
    visualize_tsdf_blocks: true
    visualize_free_space: true
    visualize_bounding_volumes: true
    include_free_space: true
    mesh_min_weight: 0.000001
    use_class_layer: true

  planning:
    verbosity: 99
    visualize_slice: true
    slice_resolution: 0.1
    slice_height: -0.5

  tracking:
    verbosity: 99
    visualize_tracking: true
